name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake python3 sqlite3
      - name: Install Python packages
        run: pip3 install uvicorn fastapi
      - name: Build project
        run: |
          mkdir build && cd build
          cmake ..
          make
      - name: Run tests
        run: |
          cd build
          ./backend/runTests
